version: '3'

services:

  vuepress_node:
    container_name: vuepress_node
    build: ./docker/node
    volumes:
      - .:/var/www/html
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      CHOKIDAR_USEPOLLING: 1
      CHOKIDAR_INTERVAL: 500
      DEV: 0
